start-at-login = true
after-login-command = []

after-startup-command = ['exec-and-forget sketchybar', 'workspace M']

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]
on-focus-changed = []
on-focused-monitor-changed = []
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30


automatically-unhide-macos-hidden-apps = false

[workspace-to-monitor-force-assignment]
S = 'main'
M = 'secondary'
B = 'secondary'
G = 'secondary'
T = 'main'
Z = 'secondary'

[[on-window-detected]]
if.app-name-regex-substring = 'helium'
run = 'move-node-to-workspace B'

[[on-window-detected]]
if.app-name-regex-substring = 'ghostty'
run = 'move-node-to-workspace G'

[[on-window-detected]]
if.app-name-regex-substring = 'slack'
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-name-regex-substring = 'telegram'
run = 'move-node-to-workspace T'

[[on-window-detected]]
if.app-name-regex-substring = 'zed'
run = 'move-node-to-workspace Z'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.window-title-regex-substring = 'picture-in-picture'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'openvpn'
run = 'move-node-to-workspace M'

[[on-window-detected]]
if.app-name-regex-substring = 'zoom'
run = 'move-node-to-workspace M'

[[on-window-detected]]
if.app-name-regex-substring = 'obsidian'
run = 'move-node-to-workspace M'

[gaps]
inner.horizontal = [{ monitor."built-in" = 6 }, 8]
inner.vertical = [{ monitor."built-in" = 6 }, 8]
outer.left = 0
outer.bottom = 0
outer.top = [{ monitor."built-in" = 3 }, 36]
outer.right = 0

[mode.main.binding]

alt-ctrl-shift-f = 'fullscreen'
alt-ctrl-f = 'layout floating tiling'

alt-slash = 'layout tiles horizontal vertical'
alt-period = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-e = 'focus down'
alt-a = 'focus up'
alt-i = 'focus right'

alt-ctrl-h = 'move left'
alt-ctrl-a = 'move down'
alt-ctrl-e = 'move up'
alt-ctrl-i = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-m = 'workspace M' # main workspace
alt-b = 'workspace B'
alt-g = 'workspace G'
alt-s = 'workspace S'
alt-t = 'workspace T'
alt-z = 'workspace Z'

alt-ctrl-m = 'move-node-to-workspace --focus-follows-window M' # main workspace
alt-ctrl-g = 'move-node-to-workspace --focus-follows-window G'
alt-ctrl-b = 'move-node-to-workspace --focus-follows-window B'
alt-ctrl-s = 'move-node-to-workspace --focus-follows-window S'
alt-ctrl-t = 'move-node-to-workspace --focus-follows-window T'
alt-ctrl-z = 'move-node-to-workspace --focus-follows-window Z'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'
alt-shift-enter = 'mode app'

alt-shift-b = 'exec-and-forget open -a /Applications/Helium.app'
alt-shift-g = 'exec-and-forget open -a /Applications/Ghostty.app'
alt-shift-s = 'exec-and-forget open -a /Applications/Slack.app'
alt-shift-t = 'exec-and-forget open -a /Applications/Telegram\ Desktop.app'
alt-shift-v = 'exec-and-forget open -a /Applications/OpenVPN\ Connect.app'
alt-shift-z = 'exec-and-forget open -a /Applications/Zed.app'
alt-shift-comma = 'exec-and-forget open -a /System/Applications/System\ Settings.app'

alt-shift-ctrl-left = 'workspace --wrap-around prev'
alt-shift-ctrl-right = 'workspace --wrap-around next'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']                # reset layout
s = ['exec-and-forget sketchybar --reload', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

alt-shift-left = ['join-with left', 'mode main']
alt-shift-down = ['join-with down', 'mode main']
alt-shift-up = ['join-with up', 'mode main']
alt-shift-right = ['join-with right', 'mode main']
